name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PICO_TOOLCHAIN_PATH: /usr/bin/arm-none-eabi-gcc
    steps:
      - run: echo "PICO_SDK_PATH=$(pwd)/pico-sdk" >> "$GITHUB_ENV"
      - run: sudo apt-get --yes update
      - run: >
          sudo apt-get --yes install
          gcc-arm-none-eabi
          libnewlib-arm-none-eabi
          cmake
          build-essential
          git
          ninja-build
          python3
      - run: git clone -b master --recurse-submodules https://github.com/raspberrypi/pico-sdk.git "$PICO_SDK_PATH"
      - uses: actions/checkout@v4
      - run: find . -type f -name 'pico_sdk_import.cmake' -print || true
      - run: make build
